= Antora Tabs
:description: Overview of using tabs in Antora.

Tabs in documentation can enhance the user experience and make information more digestible:

[tabs]
======
Linux::
+
--
This is the command specific of Linux
--

Windows::
+
--
In Windows you'll do things differently. 
--

macOS::
+
--
For macOS you can copy the same things from Linux.

Plus you'll have to add this one thing too.
--
======


What if I have the same set of tabs ?

[tabs]
======
Linux::
+
--
This is the command specific of Linux
--

Windows::
+
--
In Windows you'll do things differently. 
--

macOS::
+
--
For macOS you can copy the same things from Linux.

Plus you'll have to add this one thing too.
--
======


So it looks like their names must be different if you want to create a different context 

What if I have the same set of tabs ?

[tabs]
======
abc::
+
--
This is the command specific of Linux
--

xyz::
+
--
In Windows you'll do things differently. 
--

jkl::
+
--
For macOS you can copy the same things from Linux.

Plus you'll have to add this one thing too.
--
======