name: Trigger redpanda-docs-antora

on:
  push:
    branches: [dev]
  #repository_dispatch:
    #types: [trigger-redpanda-docs-antora]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Download helm-docs
        run: |
          curl -sL https://github.com/norwoodj/helm-docs/releases/download/v1.11.0/helm-docs_1.11.0_Linux_x86_64.tar.gz | tar xz
          
      - name: Add helm-docs to $PATH
        run: |
          echo "helm-docs" >> $GITHUB_PATH
          sudo mv helm-docs /usr/local/bin/

      - name: Checkout helm-charts repository
        uses: actions/checkout@v2
        with:
          repository: redpanda-data/helm-charts

      - name: Generate Helm Docs
        run: |
          helm-docs
          ls

      - name: Copy Helm Docs output to redpanda-docs-antora
        run: |
          cp charts/redpanda/README.md redpanda-docs-antora/docs/reference/
          ls
        working-directory: ${{ github.workspace }}
        
      - name: Commit changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add redpanda-docs-antora/docs/reference/*
          git commit -m "Add updated Helm Docs"
          git push
        working-directory: ${{ github.workspace }}
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
